# Generated by Django 5.1.4 on 2025-11-08 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visual', models.FileField(null=True, upload_to='submissions/')),
                ('file_type', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=None, null=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('challenge__isnull', False), ('spot__isnull', False), _connector='OR'), name='userinteraction_basechallengeinteraction_submissionchallenge_or_spot_not_null')],
            },
        ),
    ]
