# Generated by Django 5.1.4 on 2025-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Event', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, max_length=100, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('sport', models.CharField(choices=[('PK', 'Parkour')], default='PK', max_length=2)),
                ('state', models.CharField(choices=[('HI', 'Hidden'), ('AC', 'Active'), ('CL', 'Closed')], default='HI', max_length=2)),
                ('challenge_type', models.CharField(choices=[('CH', 'Challenge'), ('SP', 'Spot')], default='CH', max_length=2)),
                ('n_challenges_for_leaderboard', models.IntegerField(default=5)),
                ('map_region', models.CharField(choices=[('SO', 'Sofia'), ('PL', 'Plovdiv'), ('BG', 'Bulgaria')], default='SO', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
