# Generated by Django 5.1.4 on 2025-11-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualsQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.URLField()),
                ('file_type', models.CharField(max_length=50)),
            ],
        ),
    ]
